language: node_js
node_js:
    - '10'
    - '12'
cache:
    directories:
        - node_modules
script:
    - npm run lint
    - npm t
deploy:
    provider: npm
    email: mjeightyfive@gmail.com
    api_key:
        secure: R99xoGPQt2hRSfR53SCbN0WrLvydSZ5nKNRyo/xVUQHTlUKrscxzrV9/bvtAHKHy9hfjwIX88zTtQ+CzcKgslVpP3d3WPiVOJywBEEKFZH4TpKYweov9P40F8+QRlPL2+un9hfh1nXkzk44t9/sosXIGB9iKACixiYwkKTWtdjCQWIXQPB2NjhGF5WuQ1CQWKevaz0o2pYWtx5wBYwEUOHJbeapw2U1BdTxVwN7FwSxANvzyPlpcTRfZla1kK/uedecImktVr1fwkN5clWFPXpOrLpVbx/Q79tU91t+BZ61sst2wU8a5lFw+CFrLxv/0x16GsBhZpcbQ+ExNQuONjeMSHnLZnF62yM0jD4ClC2xIS/o/QBN8cNNlZ+JFWWL1nV5sPQUGd1Oo6McFVbFIyVq+omPG8RHnnl14oB00bobFYjK8S893ikfpIhhJQxzcg9THPQmN1cZP5n58EdCcEMixv3QxxZ/4xnLnknxDIBCQyTrYdPddlxlGoDDfcw22Fkg2m8WvxsS9tWzm3ZaecyjOsicCYhwq4N89+oDG1WPcgO3SwLtcfDigBT8kdx5jz3TvKICZaAJ6dpxtzGtBxSwkj3yvTLGvSJX2TUREooltJlurBsdtltRZq5qBvQVKZwpWucU3kiN2uluq32uHgDXFqOTFa7gATpM8iSBUkkc=
    on:
        branch: master
        repo: mjeightyfive/eslint-config
