name: release

on:
    push:
        branches:
            - master
        tags:
            - '*'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v1

            - name: Release
              uses: docker://antonyurchenko/git-release:latest
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
